# Use a Python image as the base
FROM python:3.9-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the server requirements file and install dependencies
COPY server/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the server files into the container
COPY server/ /app/server/

# Copy the client folder into the /app directory to have the static files and HTML templates available
COPY client/ /app/client/
COPY  model/  /app/model/

# Expose port 5000 for the Flask application
EXPOSE 5000

# Run the Flask application
CMD ["python", "server/server.py"]