# Use the official Python image from the Docker Hub
FROM python:3.8

# Set the working directory to the server directory
WORKDIR /app/BangloreHomePrices/server

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install flask numpy scikit-learn

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Run server.py when the container launches
CMD ["python", "server.py"]
