# Use the official Python image from the Docker Hub
FROM python:3.8

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app   
FROM python:3.8
WORKDIR /app
COPY . /app
RUN pip install -r requirements.txt
CMD ["python", "server.py"]

COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install flask
RUN pip install numpy
RUN pip install scikit-learn


# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable
#ENV FLASK_APP=server.py

# Run app.py when the container launches
CMD ["python", "server.py"]
#CMD ["flask", "run", "--host=0.0.0.0"]